version: "3.8"
services:
  app:
    env_file: ./backend/.env
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    container_name: "app"
    volumes:
      - ./backend:/usr/local/src
  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    container_name: "web"
    volumes:
      - ./backend:/usr/local/src
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /usr/local/src
  db:
    env_file: ./backend/.env
    build: ./infra/mysql
    container_name: "db"
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306
  db2:
    build: ./infra/postgres
    container_name: "db2"
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: laravel_sns
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev111
      POSTGRES_ROOT_PASSWORD: GOnZ0k5
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/postgresql/data
  # mailhog:
  #   image: mailhog/mailhog
  #   container_name: "mailhog"
  #   ports:
  #     - 8025:8025
volumes:
  db-store:
  db_data: {}
