version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    container_name: 'app'
    volumes:
      - ./backend:/usr/local/src
  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/usr/local/src
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /usr/local/src
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

volumes:
  db-store:
